APT::FTPArchive::Release::Origin "Reuben Institute";
APT::FTPArchive::Release::Label "Reuben Institute Audio";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "all arm64 amd64";
APT::FTPArchive::Release::Components "main";
